# Generated by Django 6.0.2 on 2026-02-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='market',
            fields=[
                ('super_id', models.IntegerField()),
                ('super_name', models.CharField(max_length=255)),
                ('super_stock', models.IntegerField()),
                ('market_count', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'market',
            },
        ),
    ]
