# Generated by Django 6.0.2 on 2026-03-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('inventory_count', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=250)),
                ('product_id', models.IntegerField()),
                ('product_stock', models.IntegerField()),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
        migrations.CreateModel(
            name='market',
            fields=[
                ('super_id', models.IntegerField()),
                ('super_name', models.CharField(max_length=255)),
                ('super_stock', models.IntegerField()),
                ('market_count', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'market',
            },
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('staff_count', models.AutoField(primary_key=True, serialize=False)),
                ('staff_id', models.IntegerField()),
                ('staff_password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='staff_logs',
            fields=[
                ('staff_logs_count', models.AutoField(primary_key=True, serialize=False)),
                ('staff_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('product_id', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('payment_date', models.DateTimeField()),
                ('payment_time', models.TimeField()),
            ],
            options={
                'db_table': 'staff_logs',
            },
        ),
        migrations.CreateModel(
            name='staff_reg',
            fields=[
                ('staff_count', models.AutoField(primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=255)),
                ('staff_id', models.IntegerField()),
                ('pass_word', models.CharField()),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'staff_register',
            },
        ),
    ]
