# Generated by Django 6.0.2 on 2026-02-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('inventory_count', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
    ]
