# Generated by Django 6.0.2 on 2026-02-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m1', '0002_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='product_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='product_stock',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
