# Generated by Django 6.0.2 on 2026-02-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m1', '0003_inventory_product_id_inventory_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('staff_count', models.AutoField(primary_key=True, serialize=False)),
                ('staff_id', models.IntegerField()),
                ('staff_password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'staff',
            },
        ),
    ]
