# Generated by Django 6.0.2 on 2026-02-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m1', '0004_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff_logs',
            fields=[
                ('staff_logs_count', models.AutoField(primary_key=True, serialize=False)),
                ('staff_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('product_id', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('payment_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'staff_logs',
            },
        ),
    ]
