# Generated by Django 6.0.2 on 2026-02-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m1', '0005_staff_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff_reg',
            fields=[
                ('staff_count', models.AutoField(primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=255)),
                ('staff_id', models.IntegerField()),
                ('password', models.CharField()),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'staff_register',
            },
        ),
    ]
