# Generated by Django 6.0.2 on 2026-02-18 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m1', '0006_staff_reg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff_reg',
            old_name='password',
            new_name='pass_word',
        ),
    ]
