# Generated by Django 6.0.2 on 2026-02-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m1', '0007_rename_password_staff_reg_pass_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_logs',
            name='payment_time',
            field=models.TimeField(default=2),
            preserve_default=False,
        ),
    ]
